import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { stripTypeScriptTypes } from 'node:module';
import { JSDOM } from 'jsdom';
const source = stripTypeScriptTypes(readFileSync(new URL('../src/scripts/portrait.ts', import.meta.url), 'utf8'));
test('portrait supports hover, repeat touch toggles, keyboard, and failed images', () => {
  const dom = new JSDOM('<button class="portrait-toggle" disabled aria-pressed="false"><img class="portrait-avatar"><img class="portrait-human"></button><span id="portrait-hint" hidden></span>', { runScripts: 'outside-only' });
  const w = dom.window, button = w.document.querySelector('button'), human = w.document.querySelector('.portrait-human');
  w.eval(source);
  human.dispatchEvent(new w.Event('load'));
  assert.equal(button.disabled, false);
  const pointer = (type, pointerType) => button.dispatchEvent(new w.PointerEvent(type, { pointerType }));
  const revealed = () => button.getAttribute('aria-pressed') === 'true';
  pointer('pointerenter', 'mouse');
  assert.equal(revealed(), true);
  pointer('pointerleave', 'mouse');
  assert.equal(revealed(), false);
  pointer('pointerenter', 'touch');
  assert.equal(revealed(), false);
  pointer('click', 'touch');
  assert.equal(revealed(), true);
  pointer('pointerleave', 'touch');
  assert.equal(revealed(), true);
  pointer('click', 'touch');
  assert.equal(revealed(), false);
  button.dispatchEvent(new w.MouseEvent('click', { detail: 0 }));
  assert.equal(revealed(), true);
  assert.equal(human.getAttribute('aria-hidden'), 'false');
  human.dispatchEvent(new w.Event('error'));
  assert.equal(revealed(), false);
  assert.equal(button.disabled, true);
  dom.window.close();
});
